#!/bin/sh
# script to control WAN LED (the globe LED) on DIR-825 router:
#   no working WAN => blinking orange
#   at least one working WAN => solid orange
#   at more than one but not all WAN working => blinking blue 
#   all WAN working => solid blue

onlineIfaces=$(/usr/sbin/mwan3 interfaces | grep -c "online")
enabledIfaces=$(cat /etc/config/mwan3 | grep -c "enabled '1'")

case $onlineIfaces in
   0) # no connection => blinking orange, blue is off
	echo none > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/trigger
        echo "0" > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/brightness
        echo timer > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/trigger
        echo "250" > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/delay_on
        echo "250" > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/delay_off

      ;;

   1) # 1 connection => solid orange, blue off
        echo none > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/trigger
        echo "0" > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/brightness
        echo none > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/trigger
        echo "1" > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/brightness
      ;; 

   *)
        if [ "$onlineIfaces" -lt "$enabledIfaces" ]; then
            # more than 1 OK, but not all => orange off, blue blinking
              echo none > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/trigger
              echo "0" > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/brightness
              echo timer > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/trigger
              echo "500" > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/delay_on
              echo "500" > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/delay_off
        else
            # all working => orange off, solid blue
              echo none > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/trigger
              echo "0" > /sys/devices/platform/leds-gpio/leds/d-link:orange:planet/brightness
              echo none > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/trigger
              echo "1" > /sys/devices/platform/leds-gpio/leds/d-link:blue:planet/brightness
        fi
      ;; 
esac

exit 0
