#!/bin/sh

  uci set mwan3.UMTS${1}.enabled=0 #disable use of dongle for multiwan
  uci commit mwan3

  sleep 1 #wait a second for previous change to take effect

  /root/scripts/mwan/dongleOff ${1}

exit 0
